### ISSUE TITLE
Cannot change install directory

### ISSUE THREAD

**Issue by JL2210** [mquinson/po4a#111] opened 2018-05-21 23:02 UTC
``Use of uninitialized value $Text::WrapI18N::charmap in pattern match (m//) at /usr/local/lib/perl5/site_perl/5.26.1/Text/WrapI18N.pm line 137.
Use of uninitialized value $Text::WrapI18N::charmap in pattern match (m//) at /usr/local/lib/perl5/site_perl/5.26.1/Text/WrapI18N.pm line 155.
Can't exec "/usr/bin/locale": No such file or directory at /usr/local/lib/perl5/site_perl/5.26.1/Text/WrapI18N.pm line 134.``
I cannot change the install directory. When I try to build, this error shows. How do I change it to /usr/local so locale runs correctly?

**Comment by mquinson** [comment] 2018-05-23 21:52
Hello, thanks for the feedback.

Could you please elaborate on how you tried to change the install directory, and which command led to the outlined error message, please?

Thanks, Mt.

**Comment by JL2210** [comment] 2018-05-28 13:43
I tried to change the install directory by running Build.PL with destdir=/usr/local and with --install_base /usr/local. I was running ```perl Build``` when that error came up.

**Comment by JL2210** [comment] 2018-09-29 22:19
Have you figured anything out about this?

**Comment by mquinson** [comment] 2018-09-30 22:12
Unfortunately not. Any help would be really welcome, as po4a is best maintained by its users, nowadays. Thanks in advance,

**Comment by mquinson** [comment] 2024-01-05 01:03
Hello,

looking again at the logs, the issue is (1) probably not related to your usage of destdir (2) coming from Text::WrapI18N and not po4a itself. The important part is `Can't exec "/usr/bin/locale": No such file or directory` 

Text::WrapI18N fails to determine the prefered locale on your system, and as a last resort, it tries to call the `/usr/bin/locale` binary to determine this. Are you on Linux or Windows?

Sorry for the delay, I don't have much time to devote to po4a these years...

Mt

**Comment by mquinson** [comment] 2024-01-05 15:41
I'm closing this bug report as it seems invalid to me. @JL2210 please feel free to reopen it with a comment if you disagree.

**Closed by mquinson** 2024-01-05 15:41 UTC
