### ISSUE TITLE
issue with <?hard-pagebreak?> in docbook

### ISSUE THREAD

**Issue by roptat** [mquinson/po4a#170] opened 2019-02-04 14:29 UTC
Hi,

I'm having some troubles with a docbook file: the attached file produces wrong content for the last script in the po file: it doesn't contain any line break, although the original file has some. It seems that po4a is not able to properly translate this content either. It might be related to the `<?hard-pagebreak?>`, since without it, the gettext file is generated properly.

`LANG=fr_FR.UTF-8 po4a-updatepo -f docbook -m` [hostreqs.txt](https://github.com/mquinson/po4a/files/2828394/hostreqs.txt) `-p hostreqs.fr.po`

generates:

```
#.  ANY additional lines in the script cause a pdf rendering problem
#. type: Content of: <sect1><screen><userinput><literal>
msgid ""
"<userinput>cat &gt; version-check.sh &lt;&lt; \"EOF\" <literal>#!/bin/bash # "
"Simple script to list version numbers of critical development tools export "
"LC_ALL=C bash --version | head -n1 | cut -d\" \" -f2-4 MYSH=$(readlink -f /"
"bin/sh)  echo \"/bin/sh -&gt; $MYSH\" echo $MYSH | grep -q bash || echo "
"\"ERROR: /bin/sh does not point to bash\" unset MYSH echo -n \"Binutils: \"; "
"ld --version | head -n1 | cut -d\" \" -f3- bison --version | head -n1 if [ -"
"h /usr/bin/yacc ]; then echo \"/usr/bin/yacc -> `readlink -f /usr/bin/yacc`"
"\"; elif [ -x /usr/bin/yacc ]; then echo yacc is `/usr/bin/yacc --version | "
"head -n1` else echo \"yacc not found\" fi bzip2 --version 2&gt;&amp;1 &lt; /"
"dev/null | head -n1 | cut -d\" \" -f1,6- echo -n \"Coreutils: \"; chown --"
"version | head -n1 | cut -d\")\" -f2 diff --version | head -n1 find --"
"version | head -n1 gawk --version | head -n1 if [ -h /usr/bin/awk ]; then "
"echo \"/usr/bin/awk -&gt; `readlink -f /usr/bin/awk`\"; elif [ -x /usr/bin/"
"awk ]; then echo awk is `/usr/bin/awk --version | head -n1` else echo \"awk "
"not found\" fi gcc --version | head -n1 g++ --version | head -n1 ldd --"
"version | head -n1 | cut -d\" \" -f2- # glibc version grep --version | head -"
"n1 gzip --version | head -n1 cat /proc/version m4 --version | head -n1 make "
"--version | head -n1 patch --version | head -n1 echo Perl `perl -V:version` "
"python3 --version sed --version | head -n1 tar --version | head -n1 makeinfo "
"--version | head -n1 # texinfo version xz --version | head -n1"
msgstr ""

#. type: Content of: <sect1><screen>
#: lfs-en/chapter02/hostreqs.xml:211
#, no-wrap
msgid ""
"echo 'int main(){}' &gt; dummy.c &amp;&amp; g++ -o dummy dummy.c\n"
"if [ -x dummy ]\n"
"  then echo \"g++ compilation OK\";\n"
"  else echo \"g++ compilation failed\"; fi\n"
"rm -f dummy.c dummy</literal>\n"
"EOF\n"
"\n"
"bash version-check.sh</userinput>"
msgstr ""
```

Thanks!

**Comment by mquinson** [comment] 2020-04-28 18:58
Hello,

could someone help me debugging this, please? I can reproduce it, but I'm not sure of what `<?hard-pagebreak?>` is. What are `<? ... ?>` tags in XML? 

Sorry for being so lame in XML..

Thanks for your help,
Mt.

**Comment by roptat** [comment] 2020-04-28 19:10
I'm just as lame in XML ^^'. I think it is called a processing instruction: https://en.wikipedia.org/wiki/Processing_Instruction

**Comment by mquinson** [comment] 2020-04-28 20:18
Thanks for the pointer to Processing Instruction. "<?" is not easy to search on the Internet :)

I managed to reduce your testcase to the following:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sect1 PUBLIC "-//OASIS//DTD DocBook XML V4.5//EN" "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd">

<sect1>
<screen>
Line 1
<?hard-pagebreak?>
Line 2
</screen>
</sect1>
```

It seems to me that the bug disappear if I enclose the `<screen>` in a `<para>` tag. 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sect1 PUBLIC "-//OASIS//DTD DocBook XML V4.5//EN" "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd">
 
<sect1>
<para>aaa<screen>
Line 1
<?hard-pagebreak?>
Line 2
</screen>
bbb</para>
</sect1>
```
This file results in the following PO file (only msgid are shown for brievty). This file seems correct to me.
```
#. type: Content of: <sect1><para><screen>
#, no-wrap
msgid "Line 1\n"
#. type: Content of: <sect1><para><screen>
#, no-wrap
msgid "Line 2\n"
#. type: Content of: <sect1><para>
msgid "aaa<placeholder type=\"screen\" id=\"0\"/> bbb"
```

All this is because `<screen>` is marked as placeholder in DocBook, so you should put it in a translated tag. Are you sure that it is valid to put <screen> out of any translated tag like this? I have no idea of how to process DocBook documents :)

I keep investigating to see if I can either fix it or produce a meaningful error message.

**Comment by mquinson** [comment] 2020-04-28 20:24
WRONG. I'm wrong in my previous analysis, please discard it.

**Comment by roptat** [comment] 2020-04-28 20:46
Thanks for looking into it, it's greatly appreciated :)

**Comment by mquinson** [comment] 2020-04-28 21:05
So. This file processes correctly:
```xml
<?xml version="1.0" ?>
<!DOCTYPE sect1 PUBLIC "-//OASIS//DTD DocBook XML V4.5//EN" "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd">
<sect1>
<screen><userinput>Line 1
Line 2
Line 3
Line 4
</userinput>
</screen>
</sect1>
```
It results in a uniq msgid:
```
#, no-wrap
msgid ""
"<userinput>Line 1\n"
"Line 2\n"
"Line 3\n"
"Line 4\n"
"</userinput>\n"
```

This file (where `<userinput>` was removed) also processes correctly, resulting in 2 msgid, correctly split around the processing instruction:
```xml
<?xml version="1.0" ?>
<!DOCTYPE sect1 PUBLIC "-//OASIS//DTD DocBook XML V4.5//EN" "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd">
<sect1>
<screen>Line 1
Line 2
<?hard-pagebreak?>
Line 3
Line 4
</screen>
</sect1>
```
```
#, no-wrap
msgid ""
"Line 1\n"
"Line 2\n"
#, no-wrap
msgid ""
"Line 3\n"
"Line 4\n"
```

But this file (with both `<userinput>` and `<?hard-pagebreak?>`) triggers the bug where the first chunk is wrapped as requested by `<userinput>` instead of being no-wrap as requested by the `<screen>` that encloses everything.
```xml
<?xml version="1.0" ?>
<!DOCTYPE sect1 PUBLIC "-//OASIS//DTD DocBook XML V4.5//EN" "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd">
<sect1>
<screen><userinput>Line 1
Line 2
<?hard-pagebreak?>
Line 3
Line 4
</userinput>
</screen>
</sect1>
```
```
msgid "<userinput>Line 1 Line 2"
#, no-wrap
msgid ""
"Line 3\n"
"Line 4\n"
"</userinput>\n"
```

I think I'm almost here :)

**Comment by mquinson** [comment] 2020-04-28 22:26
Ok, I think I have a working fix: _processing instructions_ should not be considered as breaking tags like they are now. I guess that the current default is historical and was never really wanted.
I am changing _processing instructions_ to be inline tags by default, with an option 'breakprocessing' to change it back to the previous behavior (PI are breaking tags).

**Closed** 2020-04-28 23:03 UTC
Labels: fmt:docbook
